apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctf.fullname" . }}-frontend
  labels: {{- include "ctf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: {{- include "ctf.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      automountServiceAccountToken: false
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet: { path: /healthz, port: http }
          livenessProbe:
            httpGet: { path: /healthz, port: http }
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.frontendSecurityContext | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctf.fullname" . }}-frontend
  labels: {{- include "ctf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: http
      name: http
